### PR TITLE
Use bittrex for exchange rate

### PR DESCRIPTION
**Pull request by cryptapus**
I also was looking for where BLOCKEXPLORER_BASE_URL_PROD was defined, but can't seem to locate it.

Can you please update myriad.thwg.org/tx/%s to http://insight-myr.cryptap.us/tx/%s (you're welcome to use the /address as well if it is ever needed...)

### CODE REVIEW

**Comment by HashEngineering** [comment]
BLOCKEXPLORER_BASE_URL_PROD is found in myriadcoinj.

**Comment by cryptapus** [comment]
got it, pull request on myriadcoinj too. Thanks for your support!

**Comment by HashEngineering** [comment]
In my testing the exchange rate changes were successful.  However the block explorer change is resulting in an exception.  It doesn't make sense to me why that change is causing the exception, but the exception is happening.

Do you have this result also, or does it work for you?

05-01 15:05:12.176  19092-19092/hashengineering.myriadcoin.wallet E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: hashengineering.myriadcoin.wallet, PID: 19092
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= http://insight-myr.cryptap.us/block/db2fcb5bbd9c5165c8bf8a04b48a1891117a5b33f84f3ee33ae46f5ecc1cdad5 }
            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1660)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
            at android.app.Activity.startActivityForResult(Activity.java:3628)
            at android.app.Activity.startActivityForResult(Activity.java:3589)
            at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:683)
            at android.support.v4.app.Fragment.startActivity(Fragment.java:783)
            at de.schildbach.wallet.ui.BlockListFragment$1.onActionItemClicked(BlockListFragment.java:170)
            at com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeCallbackWrapper.onActionItemClicked(ActionBarSherlockNative.java:238)
            at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:3069)
            at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:1081)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
            at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:231)
            at android.widget.AdapterView.performItemClick(AdapterView.java:313)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1529)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3560)
            at android.widget.AbsListView$3.run(AbsListView.java:5277)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by cryptapus** [comment]
Haven't tried to build yet.

I've updated myriadcoinj with my other block explorer, perhaps there's something in insight/node.js this has an issue with? Although the updated explorer is not as complete as insight, the request will more than likely fail for unconfirmed transactions...

**Comment by HashEngineering** [comment]
I don't think this problem has to do which site is the block explorer.  Could be wrong though.  Current version on a different device doesn't have this issue.

**Comment by HashEngineering** [comment]
I have two devices with the same problem.  Perhaps it is the URL, it is some how not recognized as a valid link and android doesn't know what to do with it.

**Pull request merged**
